# Site settings
title: Linyc ’s wording
email: linycc@sina.cn
description: > # 
 我以为我是可以适应孤独的<br/>
 而且也应该这样去做<br/>
 可当有一天我站在羊卓雍错<br/>
 我发觉我并不适应<br/>
 我希望有个人一起笑着说这真的好美
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  linyc

# Build settings
markdown: kramdown