# Site settings
title: Linyc ’s wording
email: linycc@sina.cn
description: > # 
 2014 ~ 2015 year summary<br/>
 2013/8 ~ start plan to travelling round the China.<br/>
 2013/10 ~ 2014/1 traveling round the China,than buy an iPhone.<br/>
 2014/2 ~ 2014/3 hometown.<br/>
 2014/4 ~ start to sell wallet on taobao.<br/>
 2014/10 ~ buy a macbook and start programming with iOS.<br/>
 2015/2 ~ publish the first App on AppStore.<br/>
 2015/3 ~ publish the second App on AppStore.<br/>
 </pre>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  linyc

# Build settings
markdown: kramdown